# Generated by Django 5.2.2 on 2025-06-06 12:12

import django.db.models.deletion
import location_field.models.plain
import xr_tour_guide_core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tag',
                'db_table': 'Tag',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('coordinates', location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True)),
                ('category', models.CharField(choices=[('INSIDE', 'Inside'), ('OUTSIDE', 'Outside'), ('THING', 'Thing')], default='INSIDE', max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('build_started_at', models.DateTimeField(blank=True, null=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('READY', 'Ready'), ('FAILED', 'Failed'), ('BUILDING', 'Building'), ('BUILT', 'Built'), ('SERVING', 'Serving'), ('ENQUEUED', 'Enqueued')], default='READY', max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tour',
                'verbose_name_plural': 'Tours',
                'db_table': 'Tour',
            },
        ),
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('coordinates', location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True)),
                ('description', models.TextField()),
                ('model_path', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('build_started_at', models.DateTimeField(blank=True, null=True)),
                ('default_image', models.ImageField(blank=True, null=True, storage=xr_tour_guide_core.models.MinioStorage(), upload_to=xr_tour_guide_core.models.default_image_waypoint)),
                ('pdf_item', models.FileField(blank=True, null=True, storage=xr_tour_guide_core.models.MinioStorage(), upload_to=xr_tour_guide_core.models.upload_media_item)),
                ('readme_item', models.FileField(blank=True, null=True, storage=xr_tour_guide_core.models.MinioStorage(), upload_to=xr_tour_guide_core.models.upload_media_item)),
                ('video_item', models.FileField(blank=True, null=True, storage=xr_tour_guide_core.models.MinioStorage(), upload_to=xr_tour_guide_core.models.upload_media_item)),
                ('audio_item', models.FileField(blank=True, null=True, storage=xr_tour_guide_core.models.MinioStorage(), upload_to=xr_tour_guide_core.models.upload_media_item)),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='xr_tour_guide_core.tag')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='xr_tour_guide_core.tour')),
            ],
            options={
                'verbose_name': 'Waypoint',
                'verbose_name_plural': 'Waypoints',
                'db_table': 'Waypoint',
            },
        ),
        migrations.CreateModel(
            name='WaypointViewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waypoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='xr_tour_guide_core.waypoint')),
            ],
        ),
    ]
