# Generated by Django 5.2.3 on 2025-06-16 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xr_tour_guide_core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='last_edited',
        ),
    ]
