# Generated by Django 5.2.4 on 2025-07-21 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xr_tour_guide_core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WaypointLink',
        ),
    ]
