# Generated by Django 5.2.3 on 2025-06-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xr_tour_guide_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='sub_tours',
            field=models.ManyToManyField(blank=True, related_name='parent_tours', to='xr_tour_guide_core.tour'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='category',
            field=models.CharField(choices=[('INSIDE', 'Inside'), ('OUTSIDE', 'Outside'), ('THING', 'Thing'), ('MIXED', 'Mixed')], default='INSIDE', max_length=20),
        ),
    ]
