# Generated by Django 5.2.3 on 2025-06-12 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xr_tour_guide_core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waypoint',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
