# Generated by Django 5.2.4 on 2025-07-16 09:28

import django.db.models.deletion
import xr_tour_guide_core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xr_tour_guide_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waypoint',
            name='text_item',
            field=models.FileField(blank=True, null=True, storage=xr_tour_guide_core.models.MinioStorage(), upload_to=xr_tour_guide_core.models.upload_media_item),
        ),
        migrations.CreateModel(
            name='WaypointLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('waypoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='xr_tour_guide_core.waypoint')),
            ],
        ),
    ]
