# Generated by Django 5.2.4 on 2025-07-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xr_tour_guide_core', '0002_tour_sub_tours_alter_tour_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='sub_tours',
            field=models.ManyToManyField(blank=True, null=True, related_name='parent_tours', to='xr_tour_guide_core.tour'),
        ),
    ]
