# Generated by Django 5.2.2 on 2025-06-05 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xr_tour_guide_core', '0002_tour_creation_time_tour_user_alter_tour_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'verbose_name': 'Tour', 'verbose_name_plural': 'Tours'},
        ),
    ]
