# Generated by Django 5.2.4 on 2025-07-16 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xr_tour_guide_core', '0002_waypoint_text_item_waypointlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waypoint',
            name='text_item',
        ),
    ]
