# Generated by Django 5.2.3 on 2025-06-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xr_tour_guide_core', '0002_remove_waypoint_tag_delete_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
