# Generated by Django 5.2.3 on 2025-06-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xr_tour_guide_core', '0003_alter_tour_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='counter_review',
            field=models.IntegerField(default=0),
        ),
    ]
