# Generated by Django 5.2.2 on 2025-06-05 08:39

import xr_tour_guide_core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xr_tour_guide_core', '0003_alter_tour_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='item',
            field=models.FileField(blank=True, null=True, storage=xr_tour_guide_core.models.MinioStorage(), upload_to=xr_tour_guide_core.models.upload_media_item),
        ),
    ]
