# Generated by Django 5.2.2 on 2025-06-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xr_tour_guide_core', '0004_alter_mediaitem_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='category',
            field=models.CharField(choices=[('INSIDE', 'Inside'), ('OUTSIDE', 'Outside'), ('THING', 'Thing')], default='INSIDE', max_length=20),
        ),
    ]
