# Generated by Django 5.2.2 on 2025-06-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xr_tour_guide_core', '0005_alter_tour_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='status',
            field=models.CharField(choices=[('READY', 'Ready'), ('FAILED', 'Failed'), ('BUILDING', 'Building'), ('BUILT', 'Built'), ('SERVING', 'Serving'), ('ENQUEUED', 'Enqueued')], default='READY', max_length=20),
        ),
    ]
