# Generated by Django 5.2.2 on 2025-06-06 10:24

import django.db.models.deletion
import xr_tour_guide_core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xr_tour_guide_core', '0006_tour_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waypointview',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='waypointview',
            name='waypoint',
        ),
        migrations.RemoveField(
            model_name='waypointviewimage',
            name='waypoint_view',
        ),
        migrations.AddField(
            model_name='waypoint',
            name='audio_item',
            field=models.FileField(blank=True, null=True, storage=xr_tour_guide_core.models.MinioStorage(), upload_to=xr_tour_guide_core.models.upload_media_item),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='build_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='default_image',
            field=models.ImageField(blank=True, null=True, storage=xr_tour_guide_core.models.MinioStorage(), upload_to=xr_tour_guide_core.models.default_image),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='pdf_item',
            field=models.FileField(blank=True, null=True, storage=xr_tour_guide_core.models.MinioStorage(), upload_to=xr_tour_guide_core.models.upload_media_item),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='readme_item',
            field=models.FileField(blank=True, null=True, storage=xr_tour_guide_core.models.MinioStorage(), upload_to=xr_tour_guide_core.models.upload_media_item),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='xr_tour_guide_core.tag'),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='video_item',
            field=models.FileField(blank=True, null=True, storage=xr_tour_guide_core.models.MinioStorage(), upload_to=xr_tour_guide_core.models.upload_media_item),
        ),
        migrations.AddField(
            model_name='waypointviewimage',
            name='waypoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='xr_tour_guide_core.waypoint'),
        ),
        migrations.DeleteModel(
            name='MediaItem',
        ),
        migrations.DeleteModel(
            name='WaypointView',
        ),
    ]
