name: xr_tour_guide
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  geolocator: ^14.0.0
  flutter_map_location_marker: ^10.1.0
  splash_master: "any"
  flutter_launcher_icons: ^0.14.3
  camera: ^0.11.1
  markdown_widget: ^2.3.2+8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  fonts:
    - family: point_panther
      fonts:
        - asset: assets/fonts/PointPanther.otf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/background_app.jpg
    - assets/acquedotto.jpg
    - assets/logo_app.png
    - assets/placeholder_avatar.jpg
    - assets/wine_category.jpg
    - assets/citta_categoria.jpg
    - assets/natura_categoria.jpg
    - assets/cibo_example.jpg
    - assets/montevergine.jpg
    - assets/logo_splash.png
    - assets/scritta_splash.png
    - assets/logo_icon.png
    - assets/icons/audio.png
    - assets/icons/document.png
    - assets/icons/image.png
    - assets/icons/link.png
    - assets/icons/text.png
    - assets/icons/video.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

splash_master:
  # Use to specifies the color for the splash screen
  color: '#FFFFFF'
  # Use to specifies the splash image
  image: 'assets/logo_app.png'
  # Provides content mode for splash image in iOS
  # iOS content mode options: scaleToFill, scaleAspectFit, scaleAspectFill, redraw, center, top, bottom,
  # left, right, topLeft, topRight, bottomLeft, bottomRight.
  ios_content_mode: 'center'
  # Provides gravity for splash image in Android
  # Android gravity options: center, clip_horizontal, clip_vertical, fill_horizontal, fill, center_vertical, 
  # bottom, fill_vertical, center_horizontal, top, end, left, right, start
  android_gravity: 'center'
  # Use to specifies the splash image
  # background_image: 'assets/logo_app.png'
  # Provided content mode for splash image in background for iOS
  # ios_background_content_mode: 'scaleToFill'
  # Provides gravity for background image in Android
  # Android gravity options: center, clip_horizontal, clip_vertical, fill_horizontal, fill, center_vertical, 
  # bottom, fill_vertical, center_horizontal, top, end, left, right, start
  # android_background_image_gravity: 'center'
  # Use to specifies image for android in dark mode
  # image_dark_android: 'assets/logo_app.png'
  # Provides gravity for splash image for Android in dark mode
  # android_dark_gravity_key: 'center'
  # Use to specifies the color for the splash screen for Android in dark mode
  # color_dark_android: '#000000'
  # Section to specifies the configuration for the splash in Android 12+
  android_12_and_above:
    # Provides the background color of splash screen
    color: '#FFFFFF'
    # Provides custom icon to replace the default app icon
    image: 'assets/logo_splash.png'
    # Provides branding image which is shown under main icon image. 
    branding_image: 'assets/scritta_splash.png'

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo_icon.png"

